---
spring:
  profiles: cloud
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    platform: org.hibernate.dialect.MariaDBDialect
    initialize: true
  data:
    mongodb:
      uri: ${vcap.services.todo-mongo.credentials.uri}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: create
  cloud:
    function:
      adapter: aws_lambda
    stream:
      bindings:
        metricsChannel:
          destination: metrics
        metrics:
          destination: metrics
          group: metrics-group
          consumer:
            durableSubscription: true
        input:
          destination: todo
          group: todo-group
          contentType: 'application/json'
          consumer:
            durableSubscription: true
            concurrency: 10
        output:
          destination: todo
          contentType: 'application/json'
amazon:
  aws:
    access-key-id: ${AMAZON_AWS_ACCESS_KEY_ID:replace}
    access-key-secret: ${AMAZON_AWS_ACCESS_KEY_SECRET:replace}
